In [86]:

# Path of the file to read
iowa_file_path = 'train-2.csv'

home_data = pd.read_csv(iowa_file_path)
home_data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [45]:
home_data = home_data.dropna(axis=0)

In [46]:
y = home_data.SalePrice

In [47]:
feature_names = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']

In [48]:
X = home_data[feature_names]

In [49]:
X.describe()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
count      0.0        0.0       0.0       0.0       0.0           0.0   
mean       NaN        NaN       NaN       NaN       NaN           NaN   
std        NaN        NaN       NaN       NaN       NaN           NaN   
min        NaN        NaN       NaN       NaN       NaN           NaN   
25%        NaN        NaN       NaN       NaN       NaN           NaN   
50%        NaN        NaN       NaN       NaN       NaN           NaN   
75%        NaN        NaN       NaN       NaN       NaN           NaN   
max        NaN        NaN       NaN       NaN       NaN           NaN   

       TotRmsAbvGrd  
count           0.0  
mean            NaN  
std             NaN  
min             NaN  
25%             NaN  
50%             NaN  
75%             NaN  
max             NaN

In [50]:
X.head()

Empty DataFrame
Columns: [LotArea, YearBuilt, 1stFlrSF, 2ndFlrSF, FullBath, BedroomAbvGr, TotRmsAbvGrd]
Index: []

In [51]:
X.corr()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
LotArea           NaN        NaN       NaN       NaN       NaN           NaN   
YearBuilt         NaN        NaN       NaN       NaN       NaN           NaN   
1stFlrSF          NaN        NaN       NaN       NaN       NaN           NaN   
2ndFlrSF          NaN        NaN       NaN       NaN       NaN           NaN   
FullBath          NaN        NaN       NaN       NaN       NaN           NaN   
BedroomAbvGr      NaN        NaN       NaN       NaN       NaN           NaN   
TotRmsAbvGrd      NaN        NaN       NaN       NaN       NaN           NaN   

              TotRmsAbvGrd  
LotArea                NaN  
YearBuilt              NaN  
1stFlrSF               NaN  
2ndFlrSF               NaN  
FullBath               NaN  
BedroomAbvGr           NaN  
TotRmsAbvGrd           NaN

In [52]:
home_data.duplicated().sum()

0

In [53]:
home_data.isnull().sum()

Id               0.0
MSSubClass       0.0
MSZoning         0.0
LotFrontage      0.0
LotArea          0.0
                ... 
MoSold           0.0
YrSold           0.0
SaleType         0.0
SaleCondition    0.0
SalePrice        0.0
Length: 81, dtype: float64

In [54]:
home_data['FullBath'].unique()

array([], dtype=int64)

In [55]:
home_data['BedroomAbvGr'].unique()

array([], dtype=int64)

In [56]:
home_data['TotRmsAbvGrd'].unique()

array([], dtype=int64)

In [57]:
home_data['YearBuilt'].unique()

array([], dtype=int64)

In [58]:
home_data['LotArea'].unique()

array([], dtype=int64)

In [59]:
home_data['LotArea'].max()

nan

In [60]:
home_data[home_data['LotArea'] > 150000][['YearBuilt', 'FullBath', 'BedroomAbvGr']].head()

Empty DataFrame
Columns: [YearBuilt, FullBath, BedroomAbvGr]
Index: []

In [61]:
import numpy as np


1. Find A + B, A - B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -2 & 4\\
2 & 0 & -1\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
5 & 2 & 3\\
4 & 6 & 2\\
\end{array}
\right)$

In [67]:
a = np.array([[1, -2, 4],[2, 0, -1]])
b = np.array([[5, 2, 3], [4, 6, 2]])
print(a + b)
print(a - b)

[[6 0 7]
 [6 6 1]]
[[-4 -4  1]
 [-2 -6 -3]]


2.  С = A - 3B
 
 $\\
A = \left(
\begin{array}{cccc}
1 & 2 \\
2 & -1\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
-1 & 1 \\
1 & 2\\
0 & 0\\
\end{array}
\right)$

In [70]:
a = np.array([[1,2],[2,-1], [3,0]])
b = np.array([[-1,1], [1,2],[0,0]])
c = a - 3 * b
c

array([[ 4, -1],
       [-1, -7],
       [ 3,  0]])

3. С = AB
 
 $\\
A = \left(
\begin{array}{cccc}
1 & -1 \\
2 & 0\\
3 & 0\\
\end{array}
\right), B = \left(
\begin{array}{cccc}
1 & 1 \\
2 & 0\\
\end{array}
\right)$

In [72]:
a = np.array([[1, -1], [2, 0], [3, 0]])
b = np.array([[1, 1], [2, 0]])
a @ b

array([[-1,  1],
       [ 2,  2],
       [ 3,  3]])

4. det of matrix А
 
 $\\
A = \left(
\begin{array}{cccc}
6 & -1 & 4\\
2 & 1 & 10\\
8 & 0 & 2\\
\end{array}
\right)$

In [73]:
a = np.array([[6,-1, 4], [2, 1, 10], [8, 0, 2]])
np.linalg.det(a)

-95.99999999999999

5. Find the inverted matrix and show it
 
 $\\
A = \left(
\begin{array}{cccc}
3 & 3 & -1\\
4 & 1 & 3\\
1 & -2 & -2\\
\end{array}
\right)$

In [74]:
a = np.matrix('3 3 -1; 4 1 3; 1 -2 -2')
np.linalg.inv(a)

matrix([[ 0.07407407,  0.14814815,  0.18518519],
        [ 0.2037037 , -0.09259259, -0.24074074],
        [-0.16666667,  0.16666667, -0.16666667]])

In [77]:
a = np.array([[3,3,-1],[4,1,3], [1,-2,-2]])
b = np.linalg.inv(a)
b

array([[ 0.07407407,  0.14814815,  0.18518519],
       [ 0.2037037 , -0.09259259, -0.24074074],
       [-0.16666667,  0.16666667, -0.16666667]])

In [80]:
np.linalg.det(a) 

53.999999999999986